project_name: rushstr

skip:
  go_install: true

builds:
  - id: rushstr
    binary: rushstr
    main: .
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-apple-darwin
    env:
      - RUSTFLAGS=-C target-cpu=native

archives:
  - id: tarball-linux
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_Linux_x86_64"
    builds: [rushstr]
    files:
      - LICENSE
      - README.md
      - rushstr
    goos: [linux]

  - id: dmg-macos
    format: dmg
    name_template: "{{ .ProjectName }}_{{ .Version }}_macOS_arm64"
    builds: [rushstr]
    files:
      - LICENSE
      - README.md
      - rushstr
    goos: [darwin]
    goarch: [arm64]

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: donhk
    name: rushstr
