[package]
name = "rushstr"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
rushstr-core = { path = "../rushstr-core", version = "1.0.0" }
rushstr-tui = { path = "../rushstr-tui", version = "1.0.0" }
