[package]
name = "rushstr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
ratatui.workspace = true
rushstr-core = { path = "../rushstr-core" }
rushstr-tui = { path = "../rushstr-tui" }
