[package]
name = "rushstr-tui"
version = "1.1.0"
edition = "2024"

[dependencies]
ratatui.workspace = true
anyhow.workspace = true
arboard.workspace = true
rushstr-core = { path = "../rushstr-core", version = "1.1.0" }
