[package]
name = "rushstr-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui.workspace = true
anyhow.workspace = true
arboard = "3"
rushstr-core = { path = "../rushstr-core", version = "0.1.0" }