[package]
name = "rushstr-core"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fuzzy-matcher = "0.3"
regex = "1"
sha2 = "0.10"
sled = "0.34"
bincode = "2"

[dev-dependencies]
temp-env.workspace = true
serial_test.workspace = true
